FROM python:3.10-slim-buster
ENV PYTHONUNBUFFERED=1

RUN mkdir /app
WORKDIR /app
COPY . /app/
RUN mv /app/.docker.env .env

RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000"]