# Generated by Django 4.0.6 on 2022-10-06 15:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('address_1', models.CharField(max_length=255, verbose_name='address_1')),
                ('address_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='address_2')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state', models.CharField(max_length=2, verbose_name='state')),
                ('zip_code', models.CharField(max_length=10, verbose_name='zip_code')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='email')),
                ('logo', models.CharField(max_length=255, null=True)),
                ('timezone', models.CharField(choices=[('EST', 'Est'), ('CST', 'Cst'), ('PST', 'Pst')], default='EST', max_length=3, verbose_name='timezone')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('lifecycle_updated_on', models.DateTimeField(null=True, verbose_name='lifecycle_updated_on')),
                ('lifecycle_status', models.CharField(choices=[('LEAD', 'Lead'), ('PROSPECT', 'Prospect'), ('CUSTOMER', 'Customer')], default='LEAD', max_length=40, verbose_name='lifecycle_status')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_on', models.DateTimeField(null=True, verbose_name='locked_on')),
            ],
        ),
        migrations.CreateModel(
            name='ContactTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='contacts.contact')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.contact')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactAssociate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
                ('phone_number_ext', models.IntegerField(null=True)),
                ('designation', models.CharField(max_length=100, verbose_name='designation')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='email')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_associates', to='contacts.contact')),
            ],
        ),
    ]
