# Generated by Django 4.0.6 on 2022-10-16 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_of',
        ),
        migrations.AddField(
            model_name='contact',
            name='customer_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
