# Generated by Django 4.0.6 on 2022-10-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subdomain_prefix', models.CharField(max_length=100, unique=True)),
                ('max_prospects_per_user', models.IntegerField(default=10)),
                ('prospect_cooldown_days', models.IntegerField(default=3)),
            ],
        ),
    ]
